const RolesPermisos = {
  Pastor: [
    "presentacion",
    "estylos",
    "usuarios",
    "ticker",
    "mensajes",
    "imagenes",
    "videos",
    "predicas",
    "biblia",
  ],
  Pastora: [
    "presentacion",
    "estylos",
    "usuarios",
    "ticker",
    "mensajes",
    "imagenes",
    "videos",
    "predicas",
    "biblia",
  ],
  Asistente: [
    "presentacion",
    "estylos",
    "ticker",
    "mensajes",
    "imagenes",
    "videos",
    "biblia",
  ],
  administrador: [
    "presentacion",
    "estylos",
    "usuarios",
    "ticker",
    "mensajes",
    "imagenes",
    "videos",
    "predicas",
    "biblia",
  ],
};
export default RolesPermisos;
