export const librosAntiguo = [
  { sigla: "GEN", nombre: "Génesis" },
  { sigla: "EXO", nombre: "Éxodo" },
  { sigla: "LEV", nombre: "Levítico" },
  { sigla: "NUM", nombre: "Números" },
  { sigla: "DEU", nombre: "Deuteronomio" },
  { sigla: "JOS", nombre: "Josué" },
  { sigla: "JDG", nombre: "Jueces" }, 
  { sigla: "RUT", nombre: "Rut" },
  { sigla: "1SA", nombre: "1 Samuel" },
  { sigla: "2SA", nombre: "2 Samuel" },
  { sigla: "1RE", nombre: "1 Reyes" },
  { sigla: "2RE", nombre: "2 Reyes" },
  { sigla: "1CR", nombre: "1 Crónicas" },
  { sigla: "2CR", nombre: "2 Crónicas" },
  { sigla: "EZR", nombre: "Esdras" }, 
  { sigla: "NEH", nombre: "Nehemías" },
  { sigla: "EST", nombre: "Ester" },
  { sigla: "JOB", nombre: "Job" },
  { sigla: "PSA", nombre: "Salmos" },
  { sigla: "PRO", nombre: "Proverbios" },
  { sigla: "ECC", nombre: "Eclesiastés" },
  { sigla: "SNG", nombre: "Cantares" },
  { sigla: "ISA", nombre: "Isaías" },
  { sigla: "JER", nombre: "Jeremías" },
  { sigla: "LAM", nombre: "Lamentaciones" },
  { sigla: "EZK", nombre: "Ezequiel" }, 
  { sigla: "DAN", nombre: "Daniel" },
  { sigla: "HOS", nombre: "Oseas" }, 
  { sigla: "JOL", nombre: "Joel" }, 
  { sigla: "AMO", nombre: "Amós" },
  { sigla: "OBA", nombre: "Abdías" }, 
  { sigla: "JON", nombre: "Jonás" },
  { sigla: "MIC", nombre: "Miqueas" }, 
  { sigla: "NAM", nombre: "Nahúm" }, 
  { sigla: "HAB", nombre: "Habacuc" },
  { sigla: "ZEP", nombre: "Sofonías" },
  { sigla: "HAG", nombre: "Hageo" },
  { sigla: "ZEC", nombre: "Zacarías" }, 
  { sigla: "MAL", nombre: "Malaquías" },
];

export const librosNuevo = [
  { sigla: "MAT", nombre: "S. Mateo" }, 
  { sigla: "MRK", nombre: "S. Marcos" }, 
  { sigla: "LUK", nombre: "S. Lucas" }, 
  { sigla: "JHN", nombre: "S. Juan" }, 
  { sigla: "ACT", nombre: "Hechos" }, 
  { sigla: "ROM", nombre: "Romanos" },
  { sigla: "1CO", nombre: "1 Corintios" },
  { sigla: "2CO", nombre: "2 Corintios" },
  { sigla: "GAL", nombre: "Gálatas" },
  { sigla: "EPH", nombre: "Efesios" },
  { sigla: "PHP", nombre: "Filipenses" },
  { sigla: "COL", nombre: "Colosenses" },
  { sigla: "1TH", nombre: "1 Tesalonicenses" },
  { sigla: "2TH", nombre: "2 Tesalonicenses" },
  { sigla: "1TI", nombre: "1 Timoteo" },
  { sigla: "2TI", nombre: "2 Timoteo" },
  { sigla: "TIT", nombre: "Tito" },
  { sigla: "PHM", nombre: "Filemón" },
  { sigla: "HEB", nombre: "Hebreos" },
  { sigla: "JAS", nombre: "Santiago" }, 
  { sigla: "1PE", nombre: "1 Pedro" },
  { sigla: "2PE", nombre: "2 Pedro" },
  { sigla: "1JN", nombre: "1 Juan" },
  { sigla: "2JN", nombre: "2 Juan" },
  { sigla: "3JN", nombre: "3 Juan" },
  { sigla: "JUD", nombre: "Judas" },
  { sigla: "REV", nombre: "Apocalipsis" },
];
