export const librosAntiguo = [
  { sigla: "GEN", nombre: "Génesis", capitulos: 50 },
  { sigla: "EXO", nombre: "Éxodo", capitulos: 40 },
  { sigla: "LEV", nombre: "Levítico", capitulos: 27 },
  { sigla: "NUM", nombre: "Números", capitulos: 36 },
  { sigla: "DEU", nombre: "Deuteronomio", capitulos: 34 },
  { sigla: "JOS", nombre: "Josué", capitulos: 24 },
  { sigla: "JDG", nombre: "Jueces", capitulos: 21 },
  { sigla: "RUT", nombre: "Rut", capitulos: 4 },
  { sigla: "1SA", nombre: "1 Samuel", capitulos: 31 },
  { sigla: "2SA", nombre: "2 Samuel", capitulos: 24 },
  { sigla: "1KI", nombre: "1 Reyes", capitulos: 22 },
  { sigla: "2KI", nombre: "2 Reyes", capitulos: 25 },
  { sigla: "1CH", nombre: "1 Crónicas", capitulos: 29 },
  { sigla: "2CH", nombre: "2 Crónicas", capitulos: 36 },
  { sigla: "EZR", nombre: "Esdras", capitulos: 10 },
  { sigla: "NEH", nombre: "Nehemías", capitulos: 13 },
  { sigla: "EST", nombre: "Ester", capitulos: 10 },
  { sigla: "JOB", nombre: "Job", capitulos: 42 },
  { sigla: "PSA", nombre: "Salmos", capitulos: 150 },
  { sigla: "PRO", nombre: "Proverbios", capitulos: 31 },
  { sigla: "ECC", nombre: "Eclesiastés", capitulos: 12 },
  { sigla: "SNG", nombre: "Cantares", capitulos: 8 },
  { sigla: "ISA", nombre: "Isaías", capitulos: 66 },
  { sigla: "JER", nombre: "Jeremías", capitulos: 52 },
  { sigla: "LAM", nombre: "Lamentaciones", capitulos: 5 },
  { sigla: "EZK", nombre: "Ezequiel", capitulos: 48 },
  { sigla: "DAN", nombre: "Daniel", capitulos: 12 },
  { sigla: "HOS", nombre: "Oseas", capitulos: 14 },
  { sigla: "JOL", nombre: "Joel", capitulos: 3 },
  { sigla: "AMO", nombre: "Amós", capitulos: 9 },
  { sigla: "OBA", nombre: "Abdías", capitulos: 1 },
  { sigla: "JON", nombre: "Jonás", capitulos: 4 },
  { sigla: "MIC", nombre: "Miqueas", capitulos: 7 },
  { sigla: "NAM", nombre: "Nahúm", capitulos: 3 },
  { sigla: "HAB", nombre: "Habacuc", capitulos: 3 },
  { sigla: "ZEP", nombre: "Sofonías", capitulos: 3 },
  { sigla: "HAG", nombre: "Hageo", capitulos: 2 },
  { sigla: "ZEC", nombre: "Zacarías", capitulos: 14 },
  { sigla: "MAL", nombre: "Malaquías", capitulos: 4 },
];

export const librosNuevo = [
  { sigla: "MAT", nombre: "S. Mateo", capitulos: 28 },
  { sigla: "MRK", nombre: "S. Marcos", capitulos: 16 },
  { sigla: "LUK", nombre: "S. Lucas", capitulos: 24 },
  { sigla: "JHN", nombre: "S. Juan", capitulos: 21 },
  { sigla: "ACT", nombre: "Hechos", capitulos: 28 },
  { sigla: "ROM", nombre: "Romanos", capitulos: 16 },
  { sigla: "1CO", nombre: "1 Corintios", capitulos: 16 },
  { sigla: "2CO", nombre: "2 Corintios", capitulos: 13 },
  { sigla: "GAL", nombre: "Gálatas", capitulos: 6 },
  { sigla: "EPH", nombre: "Efesios", capitulos: 6 },
  { sigla: "PHP", nombre: "Filipenses", capitulos: 4 },
  { sigla: "COL", nombre: "Colosenses", capitulos: 4 },
  { sigla: "1TH", nombre: "1 Tesalonicenses", capitulos: 5 },
  { sigla: "2TH", nombre: "2 Tesalonicenses", capitulos: 3 },
  { sigla: "1TI", nombre: "1 Timoteo", capitulos: 6 },
  { sigla: "2TI", nombre: "2 Timoteo", capitulos: 4 },
  { sigla: "TIT", nombre: "Tito", capitulos: 3 },
  { sigla: "PHM", nombre: "Filemón", capitulos: 1 },
  { sigla: "HEB", nombre: "Hebreos", capitulos: 13 },
  { sigla: "JAS", nombre: "Santiago", capitulos: 5 },
  { sigla: "1PE", nombre: "1 Pedro", capitulos: 5 },
  { sigla: "2PE", nombre: "2 Pedro", capitulos: 3 },
  { sigla: "1JN", nombre: "1 Juan", capitulos: 5 },
  { sigla: "2JN", nombre: "2 Juan", capitulos: 1 },
  { sigla: "3JN", nombre: "3 Juan", capitulos: 1 },
  { sigla: "JUD", nombre: "Judas", capitulos: 1 },
  { sigla: "REV", nombre: "Apocalipsis", capitulos: 22 },
];
